# Setup
title:        HeaiKun Learnning
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "http://heaikun.com"
paginate:     5
locale:       "en"

# About/contact
author:
  name:       hehk/heaikun
  url:        http://heaikun.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown