# Setup
theme: jekyll-theme-cayman
title:        HeaiKun Learnning
tagline:      技术栈： Linux C C++ shell Python 等. 生命不息，思考不止！ 
baseurl:      "http://heaikun.com"


# About/contact
author:
  name:       hehk/heaikun
  url:        http://heaikun.com
